name: CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */12 * * *'
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: L3tum/CPU-Benchmark-Database-Aggregator@master
    - name: push back
      run: |
          date +%s > VERSION
          git config --global user.name 'L3tum'
          git config --global user.email 'l3tum@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add -A
          git commit -am "Automated aggregation"
          git push
